/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplest.possible.implementation;

import java.util.Collections;
import java.util.List;

public class PrimeFactors {

    public <T> List<T> of(int number) {
        return Collections.emptyList();
    }
}
